spring.application.name=settlement-engine
# Server Port Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mock_bank_db
spring.datasource.username=postgres
spring.datasource.password=ShivShambhu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration (Idempotency Key Engine)
spring.data.redis.host=localhost
spring.data.redis.port=6379

